
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>Hermes Themes</title>
        <link rel="icon" type="image/x-icon" href="/mercurywhite.ico"/>
      </head>
      <body>

        {children}
      </body>
    </html>
  )
}
